export {
  CORE_100_ANATOMY_IMAGE_FILES,
  CORE_100_EXERCISE_CONTENT_ROOT,
  CORE_100_EXERCISE_COUNT,
  CORE_100_EXERCISE_PUBLIC_ROOT,
  CORE_100_EXERCISE_SLOTS,
  CORE_100_MISTAKE_IMAGE_FILES,
  CORE_100_REQUIRED_IMAGE_FILES,
  CORE_100_STAGE_IMAGE_FILES,
  CORE_100_VIDEO_FILES,
  isCore100ExerciseId,
  publicUrlForCore100Exercise,
  repoPathForCore100Exercise,
  storageVideoPathForCore100Exercise,
  type Core100ExerciseExternalId,
  type Core100MediaRelativePath,
} from "@/lib/platform/content/core-100-exercise-media";
