/**
 * Unified training strategy error taxonomy — Phase 6 hardening reference.
 * Prefer these codes at integration boundaries; domain modules may emit specifics.
 */
export const TRAINING_STRATEGY_ERROR_CODES = {
  // Strategy / profile
  MISSING_GOAL: "MISSING_GOAL",
  UNMAPPED_LEGACY_GOAL: "UNMAPPED_LEGACY_GOAL",
  UNKNOWN_GOAL: "UNKNOWN_GOAL",
  MISSING_TRAINING_FREQUENCY: "MISSING_TRAINING_FREQUENCY",
  UNSUPPORTED_TRAINING_FREQUENCY: "UNSUPPORTED_TRAINING_FREQUENCY",
  UNKNOWN_TRAINING_LOCATION: "UNKNOWN_TRAINING_LOCATION",
  CORE_100_POOL_UNAVAILABLE: "CORE_100_POOL_UNAVAILABLE",

  // Validation / generation
  PROGRAM_INVALID: "PROGRAM_INVALID",
  PROGRAM_GENERATION_BLOCKED: "PROGRAM_GENERATION_BLOCKED",
  SAFETY_RESTRICTION: "SAFETY_RESTRICTION",
  INSUFFICIENT_SAFE_EXERCISE_COVERAGE: "INSUFFICIENT_SAFE_EXERCISE_COVERAGE",
  FIXED_LOAD_FORBIDDEN: "FIXED_LOAD_FORBIDDEN",
  MISSING_GOAL_ID: "MISSING_GOAL_ID",
  MISSING_SESSIONS: "MISSING_SESSIONS",
  INVALID_SESSION_STRUCTURE: "INVALID_SESSION_STRUCTURE",

  // Assignment orchestration
  STALE_STRATEGY_CONTEXT: "STALE_STRATEGY_CONTEXT",
  STALE_ASSIGNMENT: "STALE_ASSIGNMENT",
  CANDIDATE_NOT_ASSIGNABLE: "CANDIDATE_NOT_ASSIGNABLE",
  AUTOMATED_DISABLED: "AUTOMATED_DISABLED",
  FREE_ENTITLEMENT_BLOCKED: "FREE_ENTITLEMENT_BLOCKED",
  ACTIVE_ASSIGNMENT_EXISTS: "active_assignment_exists",

  // Coach override
  OVERRIDE_BLOCKED: "OVERRIDE_BLOCKED",
  COACH_CANCELLED: "COACH_CANCELLED",

  // Entitlement / auth
  UNAUTHORIZED: "UNAUTHORIZED",
} as const;

export type TrainingStrategyErrorCode =
  (typeof TRAINING_STRATEGY_ERROR_CODES)[keyof typeof TRAINING_STRATEGY_ERROR_CODES];

/** Maps related codes to a canonical bucket for observability dashboards. */
export const ERROR_CODE_ALIASES: Record<string, TrainingStrategyErrorCode> = {
  SAFETY_RESTRICTION_VIOLATION: TRAINING_STRATEGY_ERROR_CODES.SAFETY_RESTRICTION,
  STRATEGY_RESOLUTION_FAILED: TRAINING_STRATEGY_ERROR_CODES.PROGRAM_GENERATION_BLOCKED,
  PROGRAM_REGENERATION_FAILED: TRAINING_STRATEGY_ERROR_CODES.PROGRAM_INVALID,
};

export function canonicalErrorCode(code: string): string {
  return ERROR_CODE_ALIASES[code] ?? code;
}
