/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PlatformRouteRouteImport } from './routes/_platform/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as PlatformAppIndexRouteImport } from './routes/_platform/app/index'
import { Route as PlatformAppSupportRouteImport } from './routes/_platform/app/support'
import { Route as PlatformAppStudioRouteImport } from './routes/_platform/app/studio'
import { Route as PlatformAppProgressRouteImport } from './routes/_platform/app/progress'
import { Route as PlatformAppProfileRouteImport } from './routes/_platform/app/profile'
import { Route as PlatformAppDiscoverRouteImport } from './routes/_platform/app/discover'
import { Route as PlatformAppAchievementsRouteImport } from './routes/_platform/app/achievements'
import { Route as PlatformAppProgramIndexRouteImport } from './routes/_platform/app/program/index'
import { Route as PlatformAppNutritionIndexRouteImport } from './routes/_platform/app/nutrition/index'
import { Route as PlatformAppExercisesIndexRouteImport } from './routes/_platform/app/exercises/index'
import { Route as PlatformAppToolsTimerRouteImport } from './routes/_platform/app/tools/timer'
import { Route as PlatformAppToolsCaloriesRouteImport } from './routes/_platform/app/tools/calories'
import { Route as PlatformAppNutritionShoppingRouteImport } from './routes/_platform/app/nutrition/shopping'
import { Route as PlatformAppNutritionProgressRouteImport } from './routes/_platform/app/nutrition/progress'
import { Route as PlatformAppNutritionMealRouteImport } from './routes/_platform/app/nutrition/meal'
import { Route as PlatformAppNutritionAlternativesRouteImport } from './routes/_platform/app/nutrition/alternatives'
import { Route as PlatformAppExercisesExerciseIdRouteImport } from './routes/_platform/app/exercises/$exerciseId'
import { Route as PlatformAppDiscoverSearchRouteImport } from './routes/_platform/app/discover/search'
import { Route as PlatformAppDiscoverSavedRouteImport } from './routes/_platform/app/discover/saved'
import { Route as PlatformAppDiscoverSlugRouteImport } from './routes/_platform/app/discover/$slug'
import { Route as PlatformAppProgramWorkoutIndexRouteImport } from './routes/_platform/app/program/workout/index'
import { Route as PlatformAppProgramWorkoutExerciseRouteImport } from './routes/_platform/app/program/workout/exercise'
import { Route as PlatformAppDiscoverCategorySlugRouteImport } from './routes/_platform/app/discover/category/$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRouteRoute = PlatformRouteRouteImport.update({
  id: '/_platform',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PlatformAppIndexRoute = PlatformAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformAppSupportRoute = PlatformAppSupportRouteImport.update({
  id: '/app/support',
  path: '/app/support',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformAppStudioRoute = PlatformAppStudioRouteImport.update({
  id: '/app/studio',
  path: '/app/studio',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformAppProgressRoute = PlatformAppProgressRouteImport.update({
  id: '/app/progress',
  path: '/app/progress',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformAppProfileRoute = PlatformAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformAppDiscoverRoute = PlatformAppDiscoverRouteImport.update({
  id: '/app/discover',
  path: '/app/discover',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformAppAchievementsRoute = PlatformAppAchievementsRouteImport.update({
  id: '/app/achievements',
  path: '/app/achievements',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformAppProgramIndexRoute = PlatformAppProgramIndexRouteImport.update({
  id: '/app/program/',
  path: '/app/program/',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformAppNutritionIndexRoute =
  PlatformAppNutritionIndexRouteImport.update({
    id: '/app/nutrition/',
    path: '/app/nutrition/',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const PlatformAppExercisesIndexRoute =
  PlatformAppExercisesIndexRouteImport.update({
    id: '/app/exercises/',
    path: '/app/exercises/',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const PlatformAppToolsTimerRoute = PlatformAppToolsTimerRouteImport.update({
  id: '/app/tools/timer',
  path: '/app/tools/timer',
  getParentRoute: () => PlatformRouteRoute,
} as any)
const PlatformAppToolsCaloriesRoute =
  PlatformAppToolsCaloriesRouteImport.update({
    id: '/app/tools/calories',
    path: '/app/tools/calories',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const PlatformAppNutritionShoppingRoute =
  PlatformAppNutritionShoppingRouteImport.update({
    id: '/app/nutrition/shopping',
    path: '/app/nutrition/shopping',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const PlatformAppNutritionProgressRoute =
  PlatformAppNutritionProgressRouteImport.update({
    id: '/app/nutrition/progress',
    path: '/app/nutrition/progress',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const PlatformAppNutritionMealRoute =
  PlatformAppNutritionMealRouteImport.update({
    id: '/app/nutrition/meal',
    path: '/app/nutrition/meal',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const PlatformAppNutritionAlternativesRoute =
  PlatformAppNutritionAlternativesRouteImport.update({
    id: '/app/nutrition/alternatives',
    path: '/app/nutrition/alternatives',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const PlatformAppExercisesExerciseIdRoute =
  PlatformAppExercisesExerciseIdRouteImport.update({
    id: '/app/exercises/$exerciseId',
    path: '/app/exercises/$exerciseId',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const PlatformAppDiscoverSearchRoute =
  PlatformAppDiscoverSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => PlatformAppDiscoverRoute,
  } as any)
const PlatformAppDiscoverSavedRoute =
  PlatformAppDiscoverSavedRouteImport.update({
    id: '/saved',
    path: '/saved',
    getParentRoute: () => PlatformAppDiscoverRoute,
  } as any)
const PlatformAppDiscoverSlugRoute = PlatformAppDiscoverSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PlatformAppDiscoverRoute,
} as any)
const PlatformAppProgramWorkoutIndexRoute =
  PlatformAppProgramWorkoutIndexRouteImport.update({
    id: '/app/program/workout/',
    path: '/app/program/workout/',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const PlatformAppProgramWorkoutExerciseRoute =
  PlatformAppProgramWorkoutExerciseRouteImport.update({
    id: '/app/program/workout/exercise',
    path: '/app/program/workout/exercise',
    getParentRoute: () => PlatformRouteRoute,
  } as any)
const PlatformAppDiscoverCategorySlugRoute =
  PlatformAppDiscoverCategorySlugRouteImport.update({
    id: '/category/$slug',
    path: '/category/$slug',
    getParentRoute: () => PlatformAppDiscoverRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/app/achievements': typeof PlatformAppAchievementsRoute
  '/app/discover': typeof PlatformAppDiscoverRouteWithChildren
  '/app/profile': typeof PlatformAppProfileRoute
  '/app/progress': typeof PlatformAppProgressRoute
  '/app/studio': typeof PlatformAppStudioRoute
  '/app/support': typeof PlatformAppSupportRoute
  '/app/': typeof PlatformAppIndexRoute
  '/app/discover/$slug': typeof PlatformAppDiscoverSlugRoute
  '/app/discover/saved': typeof PlatformAppDiscoverSavedRoute
  '/app/discover/search': typeof PlatformAppDiscoverSearchRoute
  '/app/exercises/$exerciseId': typeof PlatformAppExercisesExerciseIdRoute
  '/app/nutrition/alternatives': typeof PlatformAppNutritionAlternativesRoute
  '/app/nutrition/meal': typeof PlatformAppNutritionMealRoute
  '/app/nutrition/progress': typeof PlatformAppNutritionProgressRoute
  '/app/nutrition/shopping': typeof PlatformAppNutritionShoppingRoute
  '/app/tools/calories': typeof PlatformAppToolsCaloriesRoute
  '/app/tools/timer': typeof PlatformAppToolsTimerRoute
  '/app/exercises/': typeof PlatformAppExercisesIndexRoute
  '/app/nutrition/': typeof PlatformAppNutritionIndexRoute
  '/app/program/': typeof PlatformAppProgramIndexRoute
  '/app/discover/category/$slug': typeof PlatformAppDiscoverCategorySlugRoute
  '/app/program/workout/exercise': typeof PlatformAppProgramWorkoutExerciseRoute
  '/app/program/workout/': typeof PlatformAppProgramWorkoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/app/achievements': typeof PlatformAppAchievementsRoute
  '/app/discover': typeof PlatformAppDiscoverRouteWithChildren
  '/app/profile': typeof PlatformAppProfileRoute
  '/app/progress': typeof PlatformAppProgressRoute
  '/app/studio': typeof PlatformAppStudioRoute
  '/app/support': typeof PlatformAppSupportRoute
  '/app': typeof PlatformAppIndexRoute
  '/app/discover/$slug': typeof PlatformAppDiscoverSlugRoute
  '/app/discover/saved': typeof PlatformAppDiscoverSavedRoute
  '/app/discover/search': typeof PlatformAppDiscoverSearchRoute
  '/app/exercises/$exerciseId': typeof PlatformAppExercisesExerciseIdRoute
  '/app/nutrition/alternatives': typeof PlatformAppNutritionAlternativesRoute
  '/app/nutrition/meal': typeof PlatformAppNutritionMealRoute
  '/app/nutrition/progress': typeof PlatformAppNutritionProgressRoute
  '/app/nutrition/shopping': typeof PlatformAppNutritionShoppingRoute
  '/app/tools/calories': typeof PlatformAppToolsCaloriesRoute
  '/app/tools/timer': typeof PlatformAppToolsTimerRoute
  '/app/exercises': typeof PlatformAppExercisesIndexRoute
  '/app/nutrition': typeof PlatformAppNutritionIndexRoute
  '/app/program': typeof PlatformAppProgramIndexRoute
  '/app/discover/category/$slug': typeof PlatformAppDiscoverCategorySlugRoute
  '/app/program/workout/exercise': typeof PlatformAppProgramWorkoutExerciseRoute
  '/app/program/workout': typeof PlatformAppProgramWorkoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_platform': typeof PlatformRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/refund': typeof RefundRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/_platform/app/achievements': typeof PlatformAppAchievementsRoute
  '/_platform/app/discover': typeof PlatformAppDiscoverRouteWithChildren
  '/_platform/app/profile': typeof PlatformAppProfileRoute
  '/_platform/app/progress': typeof PlatformAppProgressRoute
  '/_platform/app/studio': typeof PlatformAppStudioRoute
  '/_platform/app/support': typeof PlatformAppSupportRoute
  '/_platform/app/': typeof PlatformAppIndexRoute
  '/_platform/app/discover/$slug': typeof PlatformAppDiscoverSlugRoute
  '/_platform/app/discover/saved': typeof PlatformAppDiscoverSavedRoute
  '/_platform/app/discover/search': typeof PlatformAppDiscoverSearchRoute
  '/_platform/app/exercises/$exerciseId': typeof PlatformAppExercisesExerciseIdRoute
  '/_platform/app/nutrition/alternatives': typeof PlatformAppNutritionAlternativesRoute
  '/_platform/app/nutrition/meal': typeof PlatformAppNutritionMealRoute
  '/_platform/app/nutrition/progress': typeof PlatformAppNutritionProgressRoute
  '/_platform/app/nutrition/shopping': typeof PlatformAppNutritionShoppingRoute
  '/_platform/app/tools/calories': typeof PlatformAppToolsCaloriesRoute
  '/_platform/app/tools/timer': typeof PlatformAppToolsTimerRoute
  '/_platform/app/exercises/': typeof PlatformAppExercisesIndexRoute
  '/_platform/app/nutrition/': typeof PlatformAppNutritionIndexRoute
  '/_platform/app/program/': typeof PlatformAppProgramIndexRoute
  '/_platform/app/discover/category/$slug': typeof PlatformAppDiscoverCategorySlugRoute
  '/_platform/app/program/workout/exercise': typeof PlatformAppProgramWorkoutExerciseRoute
  '/_platform/app/program/workout/': typeof PlatformAppProgramWorkoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/privacy'
    | '/quiz'
    | '/refund'
    | '/terms'
    | '/dashboard'
    | '/admin/payments'
    | '/app/achievements'
    | '/app/discover'
    | '/app/profile'
    | '/app/progress'
    | '/app/studio'
    | '/app/support'
    | '/app/'
    | '/app/discover/$slug'
    | '/app/discover/saved'
    | '/app/discover/search'
    | '/app/exercises/$exerciseId'
    | '/app/nutrition/alternatives'
    | '/app/nutrition/meal'
    | '/app/nutrition/progress'
    | '/app/nutrition/shopping'
    | '/app/tools/calories'
    | '/app/tools/timer'
    | '/app/exercises/'
    | '/app/nutrition/'
    | '/app/program/'
    | '/app/discover/category/$slug'
    | '/app/program/workout/exercise'
    | '/app/program/workout/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/privacy'
    | '/quiz'
    | '/refund'
    | '/terms'
    | '/dashboard'
    | '/admin/payments'
    | '/app/achievements'
    | '/app/discover'
    | '/app/profile'
    | '/app/progress'
    | '/app/studio'
    | '/app/support'
    | '/app'
    | '/app/discover/$slug'
    | '/app/discover/saved'
    | '/app/discover/search'
    | '/app/exercises/$exerciseId'
    | '/app/nutrition/alternatives'
    | '/app/nutrition/meal'
    | '/app/nutrition/progress'
    | '/app/nutrition/shopping'
    | '/app/tools/calories'
    | '/app/tools/timer'
    | '/app/exercises'
    | '/app/nutrition'
    | '/app/program'
    | '/app/discover/category/$slug'
    | '/app/program/workout/exercise'
    | '/app/program/workout'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_platform'
    | '/auth'
    | '/pricing'
    | '/privacy'
    | '/quiz'
    | '/refund'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/admin/payments'
    | '/_platform/app/achievements'
    | '/_platform/app/discover'
    | '/_platform/app/profile'
    | '/_platform/app/progress'
    | '/_platform/app/studio'
    | '/_platform/app/support'
    | '/_platform/app/'
    | '/_platform/app/discover/$slug'
    | '/_platform/app/discover/saved'
    | '/_platform/app/discover/search'
    | '/_platform/app/exercises/$exerciseId'
    | '/_platform/app/nutrition/alternatives'
    | '/_platform/app/nutrition/meal'
    | '/_platform/app/nutrition/progress'
    | '/_platform/app/nutrition/shopping'
    | '/_platform/app/tools/calories'
    | '/_platform/app/tools/timer'
    | '/_platform/app/exercises/'
    | '/_platform/app/nutrition/'
    | '/_platform/app/program/'
    | '/_platform/app/discover/category/$slug'
    | '/_platform/app/program/workout/exercise'
    | '/_platform/app/program/workout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PlatformRouteRoute: typeof PlatformRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  QuizRoute: typeof QuizRoute
  RefundRoute: typeof RefundRoute
  TermsRoute: typeof TermsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform': {
      id: '/_platform'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlatformRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_platform/app/': {
      id: '/_platform/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof PlatformAppIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/app/support': {
      id: '/_platform/app/support'
      path: '/app/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof PlatformAppSupportRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/app/studio': {
      id: '/_platform/app/studio'
      path: '/app/studio'
      fullPath: '/app/studio'
      preLoaderRoute: typeof PlatformAppStudioRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/app/progress': {
      id: '/_platform/app/progress'
      path: '/app/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof PlatformAppProgressRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/app/profile': {
      id: '/_platform/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof PlatformAppProfileRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/app/discover': {
      id: '/_platform/app/discover'
      path: '/app/discover'
      fullPath: '/app/discover'
      preLoaderRoute: typeof PlatformAppDiscoverRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/app/achievements': {
      id: '/_platform/app/achievements'
      path: '/app/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof PlatformAppAchievementsRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/app/program/': {
      id: '/_platform/app/program/'
      path: '/app/program'
      fullPath: '/app/program/'
      preLoaderRoute: typeof PlatformAppProgramIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/app/nutrition/': {
      id: '/_platform/app/nutrition/'
      path: '/app/nutrition'
      fullPath: '/app/nutrition/'
      preLoaderRoute: typeof PlatformAppNutritionIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/app/exercises/': {
      id: '/_platform/app/exercises/'
      path: '/app/exercises'
      fullPath: '/app/exercises/'
      preLoaderRoute: typeof PlatformAppExercisesIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/app/tools/timer': {
      id: '/_platform/app/tools/timer'
      path: '/app/tools/timer'
      fullPath: '/app/tools/timer'
      preLoaderRoute: typeof PlatformAppToolsTimerRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/app/tools/calories': {
      id: '/_platform/app/tools/calories'
      path: '/app/tools/calories'
      fullPath: '/app/tools/calories'
      preLoaderRoute: typeof PlatformAppToolsCaloriesRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/app/nutrition/shopping': {
      id: '/_platform/app/nutrition/shopping'
      path: '/app/nutrition/shopping'
      fullPath: '/app/nutrition/shopping'
      preLoaderRoute: typeof PlatformAppNutritionShoppingRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/app/nutrition/progress': {
      id: '/_platform/app/nutrition/progress'
      path: '/app/nutrition/progress'
      fullPath: '/app/nutrition/progress'
      preLoaderRoute: typeof PlatformAppNutritionProgressRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/app/nutrition/meal': {
      id: '/_platform/app/nutrition/meal'
      path: '/app/nutrition/meal'
      fullPath: '/app/nutrition/meal'
      preLoaderRoute: typeof PlatformAppNutritionMealRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/app/nutrition/alternatives': {
      id: '/_platform/app/nutrition/alternatives'
      path: '/app/nutrition/alternatives'
      fullPath: '/app/nutrition/alternatives'
      preLoaderRoute: typeof PlatformAppNutritionAlternativesRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/app/exercises/$exerciseId': {
      id: '/_platform/app/exercises/$exerciseId'
      path: '/app/exercises/$exerciseId'
      fullPath: '/app/exercises/$exerciseId'
      preLoaderRoute: typeof PlatformAppExercisesExerciseIdRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/app/discover/search': {
      id: '/_platform/app/discover/search'
      path: '/search'
      fullPath: '/app/discover/search'
      preLoaderRoute: typeof PlatformAppDiscoverSearchRouteImport
      parentRoute: typeof PlatformAppDiscoverRoute
    }
    '/_platform/app/discover/saved': {
      id: '/_platform/app/discover/saved'
      path: '/saved'
      fullPath: '/app/discover/saved'
      preLoaderRoute: typeof PlatformAppDiscoverSavedRouteImport
      parentRoute: typeof PlatformAppDiscoverRoute
    }
    '/_platform/app/discover/$slug': {
      id: '/_platform/app/discover/$slug'
      path: '/$slug'
      fullPath: '/app/discover/$slug'
      preLoaderRoute: typeof PlatformAppDiscoverSlugRouteImport
      parentRoute: typeof PlatformAppDiscoverRoute
    }
    '/_platform/app/program/workout/': {
      id: '/_platform/app/program/workout/'
      path: '/app/program/workout'
      fullPath: '/app/program/workout/'
      preLoaderRoute: typeof PlatformAppProgramWorkoutIndexRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/app/program/workout/exercise': {
      id: '/_platform/app/program/workout/exercise'
      path: '/app/program/workout/exercise'
      fullPath: '/app/program/workout/exercise'
      preLoaderRoute: typeof PlatformAppProgramWorkoutExerciseRouteImport
      parentRoute: typeof PlatformRouteRoute
    }
    '/_platform/app/discover/category/$slug': {
      id: '/_platform/app/discover/category/$slug'
      path: '/category/$slug'
      fullPath: '/app/discover/category/$slug'
      preLoaderRoute: typeof PlatformAppDiscoverCategorySlugRouteImport
      parentRoute: typeof PlatformAppDiscoverRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PlatformAppDiscoverRouteChildren {
  PlatformAppDiscoverSlugRoute: typeof PlatformAppDiscoverSlugRoute
  PlatformAppDiscoverSavedRoute: typeof PlatformAppDiscoverSavedRoute
  PlatformAppDiscoverSearchRoute: typeof PlatformAppDiscoverSearchRoute
  PlatformAppDiscoverCategorySlugRoute: typeof PlatformAppDiscoverCategorySlugRoute
}

const PlatformAppDiscoverRouteChildren: PlatformAppDiscoverRouteChildren = {
  PlatformAppDiscoverSlugRoute: PlatformAppDiscoverSlugRoute,
  PlatformAppDiscoverSavedRoute: PlatformAppDiscoverSavedRoute,
  PlatformAppDiscoverSearchRoute: PlatformAppDiscoverSearchRoute,
  PlatformAppDiscoverCategorySlugRoute: PlatformAppDiscoverCategorySlugRoute,
}

const PlatformAppDiscoverRouteWithChildren =
  PlatformAppDiscoverRoute._addFileChildren(PlatformAppDiscoverRouteChildren)

interface PlatformRouteRouteChildren {
  PlatformAppAchievementsRoute: typeof PlatformAppAchievementsRoute
  PlatformAppDiscoverRoute: typeof PlatformAppDiscoverRouteWithChildren
  PlatformAppProfileRoute: typeof PlatformAppProfileRoute
  PlatformAppProgressRoute: typeof PlatformAppProgressRoute
  PlatformAppStudioRoute: typeof PlatformAppStudioRoute
  PlatformAppSupportRoute: typeof PlatformAppSupportRoute
  PlatformAppIndexRoute: typeof PlatformAppIndexRoute
  PlatformAppExercisesExerciseIdRoute: typeof PlatformAppExercisesExerciseIdRoute
  PlatformAppNutritionAlternativesRoute: typeof PlatformAppNutritionAlternativesRoute
  PlatformAppNutritionMealRoute: typeof PlatformAppNutritionMealRoute
  PlatformAppNutritionProgressRoute: typeof PlatformAppNutritionProgressRoute
  PlatformAppNutritionShoppingRoute: typeof PlatformAppNutritionShoppingRoute
  PlatformAppToolsCaloriesRoute: typeof PlatformAppToolsCaloriesRoute
  PlatformAppToolsTimerRoute: typeof PlatformAppToolsTimerRoute
  PlatformAppExercisesIndexRoute: typeof PlatformAppExercisesIndexRoute
  PlatformAppNutritionIndexRoute: typeof PlatformAppNutritionIndexRoute
  PlatformAppProgramIndexRoute: typeof PlatformAppProgramIndexRoute
  PlatformAppProgramWorkoutExerciseRoute: typeof PlatformAppProgramWorkoutExerciseRoute
  PlatformAppProgramWorkoutIndexRoute: typeof PlatformAppProgramWorkoutIndexRoute
}

const PlatformRouteRouteChildren: PlatformRouteRouteChildren = {
  PlatformAppAchievementsRoute: PlatformAppAchievementsRoute,
  PlatformAppDiscoverRoute: PlatformAppDiscoverRouteWithChildren,
  PlatformAppProfileRoute: PlatformAppProfileRoute,
  PlatformAppProgressRoute: PlatformAppProgressRoute,
  PlatformAppStudioRoute: PlatformAppStudioRoute,
  PlatformAppSupportRoute: PlatformAppSupportRoute,
  PlatformAppIndexRoute: PlatformAppIndexRoute,
  PlatformAppExercisesExerciseIdRoute: PlatformAppExercisesExerciseIdRoute,
  PlatformAppNutritionAlternativesRoute: PlatformAppNutritionAlternativesRoute,
  PlatformAppNutritionMealRoute: PlatformAppNutritionMealRoute,
  PlatformAppNutritionProgressRoute: PlatformAppNutritionProgressRoute,
  PlatformAppNutritionShoppingRoute: PlatformAppNutritionShoppingRoute,
  PlatformAppToolsCaloriesRoute: PlatformAppToolsCaloriesRoute,
  PlatformAppToolsTimerRoute: PlatformAppToolsTimerRoute,
  PlatformAppExercisesIndexRoute: PlatformAppExercisesIndexRoute,
  PlatformAppNutritionIndexRoute: PlatformAppNutritionIndexRoute,
  PlatformAppProgramIndexRoute: PlatformAppProgramIndexRoute,
  PlatformAppProgramWorkoutExerciseRoute:
    PlatformAppProgramWorkoutExerciseRoute,
  PlatformAppProgramWorkoutIndexRoute: PlatformAppProgramWorkoutIndexRoute,
}

const PlatformRouteRouteWithChildren = PlatformRouteRoute._addFileChildren(
  PlatformRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PlatformRouteRoute: PlatformRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  QuizRoute: QuizRoute,
  RefundRoute: RefundRoute,
  TermsRoute: TermsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
