-- Nutrition preferences first: allergy + disliked foods must be collected before training time.
-- Additive/local-first. Existing assignments are never regenerated by this migration.

BEGIN;

ALTER TABLE public.client_nutrition_profiles
  ADD COLUMN IF NOT EXISTS disliked_foods TEXT[] NOT NULL DEFAULT '{}'::text[];

CREATE OR REPLACE FUNCTION public._normalize_nutrition_text_array(p_values TEXT[])
RETURNS TEXT[]
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT COALESCE(array_agg(value ORDER BY value), '{}'::text[])
  FROM (
    SELECT DISTINCT lower(btrim(raw_value)) AS value
    FROM unnest(COALESCE(p_values, '{}'::text[])) AS raw(raw_value)
    WHERE btrim(raw_value) <> '' AND char_length(btrim(raw_value)) <= 80
    LIMIT 40
  ) normalized;
$$;

CREATE OR REPLACE FUNCTION public.client_get_my_nutrition_preferences()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user UUID := auth.uid();
  v_profile public.client_nutrition_profiles%ROWTYPE;
BEGIN
  IF v_user IS NULL THEN RAISE EXCEPTION 'authentication_required' USING ERRCODE = '42501'; END IF;
  SELECT * INTO v_profile FROM public.client_nutrition_profiles WHERE client_id = v_user;
  RETURN jsonb_build_object(
    'allergy_status', COALESCE(v_profile.allergy_status, 'UNKNOWN'),
    'known_allergens', to_jsonb(COALESCE(v_profile.known_allergens, '{}'::text[])),
    'disliked_foods', to_jsonb(COALESCE(v_profile.disliked_foods, '{}'::text[]))
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.client_set_my_nutrition_preferences(
  p_status TEXT,
  p_allergens TEXT[] DEFAULT '{}'::text[],
  p_disliked_foods TEXT[] DEFAULT '{}'::text[]
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user UUID := auth.uid();
  v_status TEXT := upper(btrim(COALESCE(p_status, '')));
  v_allergens TEXT[] := public._normalize_nutrition_text_array(p_allergens);
  v_disliked TEXT[] := public._normalize_nutrition_text_array(p_disliked_foods);
BEGIN
  IF v_user IS NULL THEN RAISE EXCEPTION 'authentication_required' USING ERRCODE = '42501'; END IF;
  IF v_status NOT IN ('CONFIRMED_NONE', 'KNOWN_ALLERGIES') THEN RAISE EXCEPTION 'invalid_allergy_status' USING ERRCODE = '22023'; END IF;
  IF v_status = 'KNOWN_ALLERGIES' AND cardinality(v_allergens) = 0 THEN RAISE EXCEPTION 'allergens_required' USING ERRCODE = '22023'; END IF;

  INSERT INTO public.client_nutrition_profiles AS profile (
    client_id, allergy_status, confirmed_none_at, known_allergens,
    dietary_restrictions, disliked_foods, updated_by, updated_at
  ) VALUES (
    v_user, v_status,
    CASE WHEN v_status = 'CONFIRMED_NONE' THEN now() ELSE NULL END,
    CASE WHEN v_status = 'KNOWN_ALLERGIES' THEN v_allergens ELSE '{}'::text[] END,
    v_disliked, v_disliked, v_user, now()
  )
  ON CONFLICT (client_id) DO UPDATE SET
    allergy_status = EXCLUDED.allergy_status,
    confirmed_none_at = EXCLUDED.confirmed_none_at,
    known_allergens = EXCLUDED.known_allergens,
    dietary_restrictions = EXCLUDED.dietary_restrictions,
    disliked_foods = EXCLUDED.disliked_foods,
    updated_by = v_user,
    updated_at = now();

  RETURN public.client_get_my_nutrition_preferences();
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_set_client_nutrition_preferences(
  p_client_id UUID,
  p_status TEXT,
  p_allergens TEXT[] DEFAULT '{}'::text[],
  p_disliked_foods TEXT[] DEFAULT '{}'::text[]
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_admin UUID := public._require_admin();
  v_status TEXT := upper(btrim(COALESCE(p_status, '')));
  v_allergens TEXT[] := public._normalize_nutrition_text_array(p_allergens);
  v_disliked TEXT[] := public._normalize_nutrition_text_array(p_disliked_foods);
BEGIN
  IF p_client_id IS NULL OR NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = p_client_id) THEN RAISE EXCEPTION 'invalid_client' USING ERRCODE = '22023'; END IF;
  IF v_status NOT IN ('CONFIRMED_NONE', 'KNOWN_ALLERGIES') THEN RAISE EXCEPTION 'invalid_allergy_status' USING ERRCODE = '22023'; END IF;
  IF v_status = 'KNOWN_ALLERGIES' AND cardinality(v_allergens) = 0 THEN RAISE EXCEPTION 'allergens_required' USING ERRCODE = '22023'; END IF;

  INSERT INTO public.client_nutrition_profiles AS profile (
    client_id, allergy_status, confirmed_none_at, known_allergens,
    dietary_restrictions, disliked_foods, updated_by, updated_at
  ) VALUES (
    p_client_id, v_status,
    CASE WHEN v_status = 'CONFIRMED_NONE' THEN now() ELSE NULL END,
    CASE WHEN v_status = 'KNOWN_ALLERGIES' THEN v_allergens ELSE '{}'::text[] END,
    v_disliked, v_disliked, v_admin, now()
  )
  ON CONFLICT (client_id) DO UPDATE SET
    allergy_status = EXCLUDED.allergy_status,
    confirmed_none_at = EXCLUDED.confirmed_none_at,
    known_allergens = EXCLUDED.known_allergens,
    dietary_restrictions = EXCLUDED.dietary_restrictions,
    disliked_foods = EXCLUDED.disliked_foods,
    updated_by = v_admin,
    updated_at = now();

  PERFORM public._write_audit_event(v_admin, p_client_id, 'client_nutrition_preferences_updated', jsonb_build_object(
    'allergy_status', v_status,
    'known_allergens', to_jsonb(v_allergens),
    'disliked_foods', to_jsonb(v_disliked)
  ));

  RETURN jsonb_build_object('client_id', p_client_id, 'allergy_status', v_status, 'known_allergens', to_jsonb(v_allergens), 'disliked_foods', to_jsonb(v_disliked));
END;
$$;

CREATE OR REPLACE FUNCTION public._apply_nutrition_preferences_to_assignment()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_profile public.client_nutrition_profiles%ROWTYPE;
BEGIN
  SELECT * INTO v_profile FROM public.client_nutrition_profiles WHERE client_id = NEW.client_id;
  IF FOUND THEN
    NEW.watch_allergens := CASE WHEN v_profile.allergy_status = 'KNOWN_ALLERGIES' THEN v_profile.known_allergens ELSE '{}'::text[] END;
    NEW.resolved_snapshot := COALESCE(NEW.resolved_snapshot, '{}'::jsonb) || jsonb_build_object(
      'client_preferences', jsonb_build_object(
        'allergy_status', v_profile.allergy_status,
        'known_allergens', to_jsonb(v_profile.known_allergens),
        'disliked_foods', to_jsonb(v_profile.disliked_foods)
      )
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_apply_nutrition_preferences_to_assignment ON public.client_nutrition_assignments;
CREATE TRIGGER trg_apply_nutrition_preferences_to_assignment
  BEFORE INSERT OR UPDATE OF client_id, resolved_snapshot ON public.client_nutrition_assignments
  FOR EACH ROW EXECUTE FUNCTION public._apply_nutrition_preferences_to_assignment();

UPDATE public.client_nutrition_assignments AS assignment
SET watch_allergens = CASE WHEN profile.allergy_status = 'KNOWN_ALLERGIES' THEN profile.known_allergens ELSE '{}'::text[] END,
    resolved_snapshot = COALESCE(assignment.resolved_snapshot, '{}'::jsonb) || jsonb_build_object(
      'client_preferences', jsonb_build_object(
        'allergy_status', profile.allergy_status,
        'known_allergens', to_jsonb(profile.known_allergens),
        'disliked_foods', to_jsonb(profile.disliked_foods)
      )
    )
FROM public.client_nutrition_profiles AS profile
WHERE assignment.client_id = profile.client_id
  AND assignment.status IN ('draft', 'scheduled', 'active');

REVOKE ALL ON FUNCTION public._normalize_nutrition_text_array(TEXT[]) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public._apply_nutrition_preferences_to_assignment() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.client_get_my_nutrition_preferences() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.client_set_my_nutrition_preferences(TEXT, TEXT[], TEXT[]) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_set_client_nutrition_preferences(UUID, TEXT, TEXT[], TEXT[]) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.client_get_my_nutrition_preferences() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.client_set_my_nutrition_preferences(TEXT, TEXT[], TEXT[]) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.admin_set_client_nutrition_preferences(UUID, TEXT, TEXT[], TEXT[]) TO authenticated, service_role;

COMMIT;
